---
# tasks file for mapr-httpfs
- name: Install Packages
  apt: pkg={{ item }} state=present 
  with_items:
    - mapr-httpfs-{{httpfs_version}}.{{httpfs_build}}
  when: ansible_distribution == 'Ubuntu'

- name: Install Packages
  yum: pkg={{ item }} state=present 
  with_items:
    - mapr-httpfs-{{httpfs_version}}.{{httpfs_build}}
  when: ansible_distribution in ('CentOS', 'RedHat', 'Amazon')

- name: configure httpfs proxy user (hosts)
  hadoop_properties:
    file: /opt/mapr/httpfs/httpfs-{{httpfs_version}}/etc/hadoop/httpfs-site.xml
    name: httpfs.proxyuser.mapr.hosts
    value: '*'

- name: configure httpfs proxy user (groups)
  hadoop_properties:
    file: /opt/mapr/httpfs/httpfs-{{httpfs_version}}/etc/hadoop/httpfs-site.xml
    name: httpfs.proxyuser.mapr.groups
    value: '*'
