---
# tasks file for mapr-httpfs
- name: Install Packages
  become: yes
  become_user: root
  yum: pkg={{ item }} state=present 
  with_items:
    - mapr-httpfs-{{httpfs_version}}.{{httpfs_build}}
  when: ansible_distribution in ('CentOS', 'RedHat', 'Amazon')
  environment: proxy_env

- name: configure httpfs proxy user (hosts)
  become: yes
  become_user: '{{mapr_admin_username}}'
  hadoop_properties:
    file: /opt/mapr/httpfs/httpfs-{{httpfs_version}}/etc/hadoop/httpfs-site.xml
    name: httpfs.proxyuser.mapr.hosts
    value: '*'

- name: configure httpfs proxy user (groups)
  become: yes
  become_user: '{{mapr_admin_username}}'
  hadoop_properties:
    file: /opt/mapr/httpfs/httpfs-{{httpfs_version}}/etc/hadoop/httpfs-site.xml
    name: httpfs.proxyuser.mapr.groups
    value: '*'
